version: "3"

services:
  fastapi:
    build: .
    ports:
      - "8530:8000"
    volumes:
      - ".:/usr/app/src"
    links:
      - db
    depends_on:
      - db
    networks:
      - fastapi_mysql_network
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    networks:
      - fastapi_mysql_network

networks:
  fastapi_mysql_network:
    driver: bridge
